using System;
/*
    This file is automatically generated!
    Many modifications you make may be lost.
    With that said...
    * Edits within the contents of the <summary/> tags will be respected.
    * Edits to the Mode will be respected.

    Commented specifics are commented because they belong on nothing but powers, 
    and don't have a stated purpose.  Fill in the <summary/> tag, 
    and they will be automatically uncommented on build.  
      This is because many such specifics are either one-ofs, or equally unique.  
      Also, Powers don't care about the Specifics Dictionary as much as any other element type.
*/

namespace ParagonLib.RuleEngine
{
    public enum Specifics
    {
        // This is assigned to any specific that doesn't feature below.
        Unknown,

		/// <summary></summary>
		[Affects("Race", "Weapon", "Companion", "Familiar", "Companion (Tivaan's Companion Cards)", "Power")]
		[Usage("Content")]
		Size,

		/// <summary>Describes the base movement or affects the maximum movement of the creature</summary>
		[Affects("Race", "Armor", "Companion", "Familiar", "Companion (Tivaan's Companion Cards)", "Power", "Power (Tivaan's Companion Cards)")]
		Speed,

		/// <summary>Some ajctives describing the race</summary>
		[Affects("Race")]
		Characteristics,

		/// <summary>What visually distinguishes people of this Race?</summary>
		[Affects("Race")]
		Physical_Qualities,

		/// <summary>Tips on how to roleplay members of this race.</summary>
		[Affects("Race")]
		Playing,

		/// <summary>What kinds of lighting conditions can the race see in? Powers that change this.</summary>
		[Affects("Race", "Power (Tivaan's Companion Cards)")]
		Vision,

		/// <summary>Gives a suggested heignt range for a character in feet and inches.</summary>
		[Affects("Race")]
		Average_Height,

		/// <summary>Gives a suggested weight range for a character in pounds</summary>
		[Affects("Race")]
		Average_Weight,

		/// <summary>Lists the scores that the race gives bonuses to.</summary>
		[Affects("Race", "Power (Tivaan's Companion Cards)")]
		Ability_Scores,

		/// <summary>Lists languages granted by the race</summary>
		[Affects("Race")]
		Languages,

		/// <summary></summary>
		[Affects("Race")]
		Skill_Bonuses,

		/// <summary></summary>
		[Affects("Race")]
		Male_Names,

		/// <summary></summary>
		[Affects("Race")]
		Female_Names,

		/// <summary></summary>
		[Affects("Race", "Class", "Hybrid Class", "Racial Trait", "Class Feature", "Background", "Information", "Feat", "Internal", "Trait Package", "Companion")]
		Short_Description,

		/// <summary></summary>
		[Affects("Race")]
		Racial_Traits,

		/// <summary></summary>
		[Affects("Race")]
		Names,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class", "Build")]
		Key_Abilities,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class")]
		Implements,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class")]
		Armor_Proficiencies,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class")]
		Weapon_Proficiencies,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class")]
		Bonus_to_Defense,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class", "Companion")]
		Hit_Points_at_1st_Level,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class", "Companion")]
		Hit_Points_per_Level_Gained,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class", "Power")]
		Healing_Surges,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class", "Companion", "Power (Tivaan's Companion Cards)")]
		Trained_Skills,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class")]
		Class_Skills,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class")]
		Build_Options,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class", "Trait Package", "Class Feature")]
		[Usage("Meta")]
        _PARSED_CLASS_FEATURE,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class")]
		Role,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class")]
		Power_Source,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class")]
		Creating,

		/// <summary></summary>
		[Affects("Class", "Epic Destiny", "Paragon Path", "Hybrid Class")]
		Class_Features,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class")]
		Supplemental,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class", "Weapon Group", "Magic Item")]
		Implement,

		/// <summary></summary>
		[Affects("Class", "Epic Destiny", "Paragon Path", "Hybrid Class", "Class Feature", "Racial Trait")]
		Powers,

		/// <summary></summary>
		[Affects("Class", "Epic Destiny", "Paragon Path", "Hybrid Class")]
		Power_Name,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class")]
		_RoleElement,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class")]
		_PowerSourceElement,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class")]
		_SecondaryPowerSourceElement,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class")]
		Secondary_Abilities,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class")]
		Hybrid_Talent_Options,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class")]
		_ParentClass,

		/// <summary></summary>
		[Affects("Class", "Hybrid Class", "Paragon Path")]
		Trait_Package,

		/// <summary></summary>
		[Affects("Epic Destiny")]
		Immortality,

		/// <summary></summary>
		[Affects("Epic Destiny", "Paragon Path", "Racial Trait", "Class Feature", "Companion", "Item Set Benefit", "Power", "Feat", "Magic Item", "Companion (Tivaan's Companion Cards)", "Theme", "Internal", "Trait Package", "Ritual", "Ritual Scroll")]
		_DisplayPowers,

		/// <summary></summary>
		[Affects("Hybrid Class")]
		_BaseClass,

		/// <summary></summary>
		[Affects("Deity")]
		Alignment,

		/// <summary></summary>
		[Affects("Deity")]
		Domains,

		/// <summary></summary>
		[Affects("Feat", "Magic Item", "Companion", "Familiar", "Item Set", "Companion (Tivaan's Companion Cards)", "Class Feature")]
		Tier,

		/// <summary></summary>
		[Affects("Feat")]
		Container,

		/// <summary></summary>
		[Affects("Feat", "Companion")]
		Associated_Powers,

		/// <summary></summary>
		[Affects("Ritual", "Gear")]
		Category,

		/// <summary></summary>
		[Affects("Ritual", "Magic Item")]
		Key_Skill,

		/// <summary></summary>
		[Affects("Ritual")]
		Component_Cost,

		/// <summary></summary>
		[Affects("Ritual")]
		Duration,

		/// <summary></summary>
		[Affects("Ritual", "Racial Trait", "Class Feature", "Magic Item", "Ritual Scroll", "Power")]
		Level,

		/// <summary></summary>
		[Affects("Ritual", "Magic Item")]
		Time,

		/// <summary></summary>
		[Affects("Ritual", "Ritual Scroll")]
		Market_Price,

		/// <summary></summary>
		[Affects("Ritual", "Power", "Magic Item")]
		Prerequisite,

		/// <summary></summary>
		[Affects("Ritual", "Class Feature", "Background", "Ritual Scroll", "Feat", "Racial Trait", "Companion")]
		type,

		/// <summary></summary>
		[Affects("Ritual")]
		_RELATED_ITEMS,

		/// <summary></summary>
		[Affects("Skill", "Magic Item")]
		Key_Ability,

		/// <summary></summary>
		[Affects("Skill Usage")]
		Trained_Only,

		/// <summary></summary>
		[Affects("Skill Usage")]
		Skill,

		/// <summary></summary>
		[Affects("Racial Trait", "Class Feature", "Theme", "Feat")]
		_PARSED_SUB_FEATURES,

		/// <summary></summary>
		[Affects("Racial Trait", "Weapon")]
		InternalOnly,

		/// <summary></summary>
		[Affects("Racial Trait", "Class Feature", "Weapon", "Item Set Benefit", "Internal", "Background Choice", "CountsAsRace", "CountsAsClass", "Ritual Scroll", "Grants", "Feat", "Power", "Category", "Magic Item", "Build Suggestions")]
		_SupportsID,

		/// <summary></summary>
		[Affects("Class Feature", "Build", "Power", "Racial Trait")]
		Class,

		/// <summary></summary>
		[Affects("Class Feature")]
		Usage,

		/// <summary></summary>
		[Affects("Class Feature", "Racial Trait")]
		_PARSED_CHILD_FEATURES,

		/// <summary></summary>
		[Affects("Class Feature", "Magic Item")]
		_ImplementForPower,

		/// <summary></summary>
		[Affects("Class Feature", "Racial Trait")]
		Damage_Stat,

		/// <summary></summary>
		[Affects("Class Feature", "Feat")]
		_RequiresID,

		/// <summary></summary>
		[Affects("Build")]
		Suggested,

		/// <summary></summary>
		[Affects("Build", "Trait Package", "Class", "Hybrid Class")]
		_SUGGESTED_FEATS,

		/// <summary></summary>
		[Affects("Build", "Paragon Path")]
		_SUGGESTED_POWERS,

		/// <summary></summary>
		[Affects("Armor", "Weapon", "Superior Implement", "Gear")]
		Full_Text,

		/// <summary></summary>
		[Affects("Armor", "Weapon", "Superior Implement", "Gear", "Magic Item")]
		Weight,

		/// <summary></summary>
		[Affects("Armor")]
		Armor_Bonus,

		/// <summary></summary>
		[Affects("Armor")]
		Minimum_Enhancement_Bonus,

		/// <summary></summary>
		[Affects("Armor", "Power")]
		Check,

		/// <summary></summary>
		[Affects("Armor", "Weapon", "Superior Implement", "Gear", "Magic Item", "Power")]
		Gold,

		/// <summary></summary>
		[Affects("Armor", "Magic Item", "Feat", "Power", "Power (Tivaan's Companion Cards)")]
		Special,

		/// <summary></summary>
		[Affects("Armor", "Weapon")]
		Armor_Type,

		/// <summary></summary>
		[Affects("Armor", "Weapon", "Superior Implement", "Gear", "Magic Item")]
		Item_Slot,

		/// <summary></summary>
		[Affects("Armor", "Weapon")]
		Armor_Category,

		/// <summary></summary>
		[Affects("Weapon", "Magic Item")]
		Range,

		/// <summary></summary>
		[Affects("Weapon", "Companion")]
		Damage,

		/// <summary></summary>
		[Affects("Weapon")]
		Proficiency_Bonus,

		/// <summary></summary>
		[Affects("Weapon")]
		_Primary_End,

		/// <summary></summary>
		[Affects("Weapon")]
		Weapon_Category,

		/// <summary></summary>
		[Affects("Weapon")]
		Hands_Required,

		/// <summary></summary>
		[Affects("Weapon", "Superior Implement")]
		Group,

		/// <summary></summary>
		[Affects("Weapon", "Superior Implement", "Magic Item")]
		Properties,

		/// <summary></summary>
		[Affects("Weapon", "Gear")]
		Silver,

		/// <summary></summary>
		[Affects("Weapon")]
		_Secondary_End,

		/// <summary></summary>
		[Affects("Weapon")]
		_IncludeImprovised,

		/// <summary></summary>
		[Affects("Weapon", "Magic Item")]
		Critical,

		/// <summary></summary>
		[Affects("Weapon", "Magic Item")]
		Enhancement,

		/// <summary></summary>
		[Affects("Weapon")]
		Additional_Slot,

		/// <summary></summary>
		[Affects("Superior Implement", "Magic Item")]
		WeaponEquiv,

		/// <summary></summary>
		[Affects("Superior Implement")]
		_DamageType,

		/// <summary></summary>
		[Affects("Gear")]
		Copper,

		/// <summary></summary>
		[Affects("Gear")]
		_RelatedElement,

		/// <summary></summary>
		[Affects("Gear")]
		count,

		/// <summary></summary>
		[Affects("Gear", "Magic Item")]
		_Monster,

		/// <summary></summary>
		[Affects("Magic Item", "Power")]
		Magic_Item_Type,

		/// <summary></summary>
		[Affects("Magic Item", "Item Set Benefit")]
		_Item_Set_ID,

		/// <summary></summary>
		[Affects("Magic Item")]
		Armor,

		/// <summary></summary>
		[Affects("Magic Item", "Power", "Class Feature")]
		Weapon,

		/// <summary></summary>
		[Affects("Magic Item", "Power")]
		Requirement,

		/// <summary></summary>
		[Affects("Magic Item", "Companion", "Familiar", "Power")]
		Power,

		/// <summary></summary>
		[Affects("Magic Item")]
		_Rarity,

		/// <summary></summary>
		[Affects("Magic Item")]
		Granted_Powers,

		/// <summary></summary>
		[Affects("Magic Item", "Power", "Gear")]
		Property,

		/// <summary></summary>
		[Affects("Background")]
		Common_Knowledge,

		/// <summary></summary>
		[Affects("Background")]
		Benefit,

		/// <summary></summary>
		[Affects("Background")]
		Campaign,

		/// <summary></summary>
		[Affects("Background")]
		Associated_Skills,

		/// <summary></summary>
		[Affects("Background")]
		Associated_Languages,

		/// <summary></summary>
		[Affects("source")]
		IsBeta,

		/// <summary></summary>
		[Affects("Companion", "Companion (Tivaan's Companion Cards)", "Power (Tivaan's Companion Cards)")]
		Strength,

		/// <summary></summary>
		[Affects("Companion", "Companion (Tivaan's Companion Cards)", "Power (Tivaan's Companion Cards)")]
		Intelligence,

		/// <summary></summary>
		[Affects("Companion", "Companion (Tivaan's Companion Cards)", "Power (Tivaan's Companion Cards)")]
		Wisdom,

		/// <summary></summary>
		[Affects("Companion", "Companion (Tivaan's Companion Cards)", "Power (Tivaan's Companion Cards)")]
		Dexterity,

		/// <summary></summary>
		[Affects("Companion", "Companion (Tivaan's Companion Cards)", "Power (Tivaan's Companion Cards)")]
		Constitution,

		/// <summary></summary>
		[Affects("Companion", "Companion (Tivaan's Companion Cards)", "Power (Tivaan's Companion Cards)")]
		Charisma,

		/// <summary></summary>
		[Affects("Companion")]
		Attack_Bonus,

		/// <summary></summary>
		[Affects("Companion", "Companion (Tivaan's Companion Cards)")]
		Armor_Class,

		/// <summary></summary>
		[Affects("Companion", "Companion (Tivaan's Companion Cards)")]
		Fortitude_Defense,

		/// <summary></summary>
		[Affects("Companion", "Companion (Tivaan's Companion Cards)")]
		Reflex_Defense,

		/// <summary></summary>
		[Affects("Companion", "Companion (Tivaan's Companion Cards)")]
		Will_Defense,

		/// <summary></summary>
		[Affects("Companion", "Familiar", "Power")]
		Secondary_Speed,

		/// <summary></summary>
		[Affects("Companion", "Power", "Power (Tivaan's Companion Cards)")]
		Attack,

		/// <summary></summary>
		[Affects("Companion", "Companion (Tivaan's Companion Cards)")]
		Ability_Score,

		/// <summary></summary>
		[Affects("Companion")]
		Charge,

		/// <summary></summary>
		[Affects("Companion", "Power")]
		Combat_Advantage,

		/// <summary></summary>
		[Affects("Companion")]
		Opportunity_Attacks,

		/// <summary></summary>
		[Affects("Companion", "God Fragment", "Companion (Tivaan's Companion Cards)", "Power", "Familiar")]
		Quirks,

		/// <summary></summary>
		[Affects("Companion")]
		Companion_Power,

		/// <summary></summary>
		[Affects("Familiar", "God Fragment", "Power")]
		Constant_Benefits,

		/// <summary></summary>
		[Affects("Familiar", "Power", "Power (Tivaan's Companion Cards)")]
		Senses,

		/// <summary></summary>
		[Affects("Item Set")]
		Lore,

		/// <summary></summary>
		[Affects("Item Set")]
		Set_Items,

		/// <summary></summary>
		[Affects("Item Set")]
		Benefits,

		/// <summary></summary>
		[Affects("Item Set Benefit")]
		Piece_Count,

		/// <summary></summary>
		[Affects("God Fragment")]
		Deity,

		/// <summary></summary>
		[Affects("God Fragment", "Power", "Power (Tivaan's Companion Cards)")]
		Action_Type,

		/// <summary></summary>
		[Affects("God Fragment", "Power")]
		Effect,

		/// <summary></summary>
		[Affects("God Fragment", "Power", "Power (Tivaan's Companion Cards)")]
		Keywords,

		/// <summary></summary>
		[Affects("God Fragment", "Power")]
		Trigger,

		/// <summary></summary>
		[Affects("God Fragment", "Power", "Power (Tivaan's Companion Cards)")]
		Power_Usage,

		/// <summary></summary>
		[Affects("Background Choice")]
		_IsBenefit,

		/// <summary>For more info about the source, look here.</summary>
		[Affects("source")]
		URL,

		/// <summary>When was the Sourcebook released?</summary>
		[Affects("source")]
		Release_Date,

		/// <summary></summary>
		[Affects("Feat", "Companion")]
		Associated_Power_Info,

		/// <summary></summary>
		[Affects("Power")]
		_SkillPower,

		/// <summary></summary>
		[Affects("Power", "Power (Tivaan's Companion Cards)")]
		Display,

		/// <summary></summary>
		[Affects("Power", "Power (Tivaan's Companion Cards)")]
		Attack_Type,

		/// <summary></summary>
		[Affects("Power", "Power (Tivaan's Companion Cards)")]
		Target,

		/// <summary></summary>
		[Affects("Power")]
		_Censure_of_Unity,

		/// <summary></summary>
		[Affects("Power", "Power (Tivaan's Companion Cards)")]
		Hit,

		/// <summary></summary>
		[Affects("Power")]
		_Associated_Feats,

		/// <summary></summary>
		[Affects("Power")]
		Power_Type,

		/// <summary></summary>
		[Affects("Class Feature", "Racial Trait", "Trait Package")]
		_CS_ShortDescription,

		/// <summary></summary>
		[Affects("Power")]
		_ChildPower,

		/// <summary></summary>
		[Affects("Power")]
		_ParentPower,

		/// <summary></summary>
		[Affects("Power")]
		_Artful_Dodger,

		/// <summary></summary>
		[Affects("Power")]
		_Weapon,

		/// <summary></summary>
		[Affects("Power")]
		Miss,

		/// <summary></summary>
		[Affects("Power")]
		_Special,

		/// <summary></summary>
		[Affects("Power")]
		_Censure_of_Pursuit,

		/// <summary></summary>
		[Affects("Power")]
		_Primal_Predator,

		/// <summary></summary>
		[Affects("Power")]
		_Bloodbond,

		/// <summary></summary>
		[Affects("Power")]
		_ParentFeature,

		/// <summary></summary>
		[Affects("Power")]
		Targets,

		/// <summary></summary>
		[Affects("Power")]
		Primary_Attack,

		/// <summary></summary>
		[Affects("Power")]
		_Secondary_Attack,

		/// <summary></summary>
		[Affects("Power")]
		_Hit,

		/// <summary></summary>
		[Affects("Power")]
		_Miss,

		/// <summary></summary>
		[Affects("Power")]
		_Subclasses,

		/// <summary></summary>
		[Affects("Power")]
		_Minor_Action,

		/// <summary></summary>
		[Affects("Power")]
		_Move_Action,

		/// <summary></summary>
		[Affects("Power")]
		_Free_Action,

		/// <summary></summary>
		[Affects("Power")]
		Sustain_Minor,

		/// <summary></summary>
		[Affects("Power")]
		_Aftereffect,

		/// <summary></summary>
		[Affects("Power")]
		_Resourceful_Presence,

		/// <summary></summary>
		[Affects("Power")]
		_AugmentParent,

		/// <summary></summary>
		[Affects("Weapon", "Magic Item")]
		_AlternateSlot,

		/// <summary></summary>
		[Affects("Level")]
		XP_Needed,

		/// <summary></summary>
		[Affects("Power")]
		_Infernal_Pact,

		/// <summary></summary>
		[Affects("Power")]
		Primary_Target,

		/// <summary></summary>
		[Affects("Power")]
		_Secondary_Target,

		/// <summary></summary>
		[Affects("Power")]
		_Brutal_Scoundrel,

		/// <summary></summary>
		[Affects("Power")]
		_Star_Pact,

		/// <summary></summary>
		[Affects("Power")]
		_First_Failed_Saving_Throw,

		/// <summary></summary>
		[Affects("Power")]
		_BasicAttack,

		/// <summary></summary>
		[Affects("Power")]
		_Attack,

		/// <summary></summary>
		[Affects("Power")]
		_Tertiary_Target,

		/// <summary></summary>
		[Affects("Power")]
		_Aegis_of_Assault,

		/// <summary></summary>
		[Affects("Power")]
		_Fey_Pact,

		/// <summary></summary>
		[Affects("Power")]
		_Ruthless_Ruffian,

		/// <summary></summary>
		[Affects("Power")]
		_Covenant_of_Wrath,

		/// <summary></summary>
		[Affects("Power")]
		_Covenant_of_Malediction,

		/// <summary></summary>
		[Affects("Power")]
		_Covenant_of_Preservation,

		/// <summary></summary>
		[Affects("Power")]
		_Inspiring_Presence,

		/// <summary></summary>
		[Affects("Power")]
		Aftereffect,

		/// <summary></summary>
		[Affects("Power")]
		Sustain_Standard,

		/// <summary></summary>
		[Affects("Power")]
		_Sustain_Minor,

		/// <summary></summary>
		[Affects("Power")]
		_Cunning_Sneak,

		/// <summary></summary>
		[Affects("Power")]
		_Effect,

		/// <summary></summary>
		[Affects("Power")]
		Aegis_of_Assault,

		/// <summary></summary>
		[Affects("Power")]
		Channel_Divinity,

		/// <summary></summary>
		[Affects("Power")]
		Aegis_of_Shielding,

		/// <summary></summary>
		[Affects("Power")]
		_Secondary_Targets,

		/// <summary></summary>
		[Affects("Power")]
		_Dark_Pact,

		/// <summary></summary>
		[Affects("Power")]
		Dark_Pact,

		/// <summary></summary>
		[Affects("Power")]
		Effects,

		/// <summary></summary>
		[Affects("Power")]
		_Tertiary_Attack,

		/// <summary></summary>
		[Affects("Power")]
		_Ruthless_Ruffians,

		/// <summary></summary>
		[Affects("Power")]
		_Afftereffect,

		/// <summary></summary>
		[Affects("Power")]
		_Tactical_Presence,

		/// <summary></summary>
		[Affects("Power")]
		_Virtue_of_Cunning,

		/// <summary></summary>
		[Affects("Power")]
		Virtue_of_Valor,

		/// <summary></summary>
		[Affects("Power")]
		_Virtue_of_Valor,

		/// <summary></summary>
		[Affects("Power")]
		Artful_Dodger,

		/// <summary></summary>
		[Affects("Power")]
		_Bravura_Presence,

		/// <summary></summary>
		[Affects("Power")]
		Augment,

		/// <summary></summary>
		[Affects("Power")]
		_AugmentVersions,

		/// <summary></summary>
		[Affects("Power")]
		_Attack_Type,

		/// <summary></summary>
		[Affects("Power")]
		_Target,

		/// <summary></summary>
		[Affects("Power")]
		_Primal_Guardian,

		/// <summary></summary>
		[Affects("Power")]
		_Storm_Magic,

		/// <summary></summary>
		[Affects("Power")]
		_Opportunity_Attack,

		/// <summary></summary>
		[Affects("Power")]
		_Censure_of_Retribution,

		/// <summary></summary>
		[Affects("Power")]
		_Virtue_of_Prescience,

		/// <summary></summary>
		[Affects("Power")]
		Virtue_of_Prescience,

		/// <summary></summary>
		[Affects("Power")]
		_Dragon_Magic,

		/// <summary></summary>
		[Affects("Power")]
		_Cosmic_Magic,

		/// <summary></summary>
		[Affects("Power")]
		Wild_Magic,

		/// <summary></summary>
		[Affects("Power")]
		_Aegis_of_Ensnarement,

		/// <summary></summary>
		[Affects("Power")]
		_Wild_Magic,

		/// <summary></summary>
		[Affects("Power")]
		Dragon_Magic,

		/// <summary></summary>
		[Affects("Power")]
		Secondary_Target,

		/// <summary></summary>
		[Affects("Power")]
		Secondary_Attack,

		/// <summary></summary>
		[Affects("Power")]
		_Covenant_of_Perservation,

		/// <summary></summary>
		[Affects("Power")]
		_Standard_action,

		/// <summary></summary>
		[Affects("Power")]
		_Seconday_Attack,

		/// <summary></summary>
		[Affects("Power")]
		_Aegis_of_Shielding,

		/// <summary></summary>
		[Affects("Power")]
		Afftereffect,

		/// <summary></summary>
		[Affects("Power")]
		_Each_Additional_Failed_Saving_Throw,

		/// <summary></summary>
		[Affects("Power")]
		_Stalker_Spirit,

		/// <summary></summary>
		[Affects("Power")]
		_Protector_Spirit,

		/// <summary></summary>
		[Affects("Power")]
		_Aegis_of_Ensarement,

		/// <summary></summary>
		[Affects("Power")]
		_First_Failed_Save,

		/// <summary></summary>
		[Affects("Power")]
		Infernal_Pact_or_Vestige_Pact,

		/// <summary></summary>
		[Affects("Power")]
		_Vestige_Pact,

		/// <summary></summary>
		[Affects("Power")]
		_Second_Failed_Save,

		/// <summary></summary>
		[Affects("Power")]
		_Standard_Acton,

/*
		/// <summary></summary>
		[Affects("Power")]
		â€¢_Standart_Action,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		â€¢_Opportunity_Attack,

*/
		/// <summary></summary>
		[Affects("Power")]
		_Immediate_Interrupt,

		/// <summary></summary>
		[Affects("Power")]
		Removed,

		/// <summary></summary>
		[Affects("Power", "Power (Tivaan's Companion Cards)")]
		Minor_Action,

		/// <summary></summary>
		[Affects("Power")]
		Opportunity_Attack,

		/// <summary></summary>
		[Affects("Power")]
		Each_Failed_Saving_Throw,

		/// <summary></summary>
		[Affects("Power")]
		Secondary_Targets,

		/// <summary></summary>
		[Affects("Power")]
		First_Failed_Save,

		/// <summary></summary>
		[Affects("Power")]
		Second_Failed_Save,

		/// <summary></summary>
		[Affects("Power")]
		Sustain_Move,

		/// <summary></summary>
		[Affects("Power")]
		_Secondary_Damage,

		/// <summary></summary>
		[Affects("Power")]
		_Beast,

		/// <summary></summary>
		[Affects("Power")]
		Beast,

		/// <summary></summary>
		[Affects("Power")]
		Ruthless_Ruffian,

		/// <summary></summary>
		[Affects("Power")]
		_KeyAbilityAs,

		/// <summary></summary>
		[Affects("Power")]
		_ADDITIONAL_USES,

		/// <summary></summary>
		[Affects("Power")]
		_Whirling_Slayer,

		/// <summary></summary>
		[Affects("Power")]
		_Rageblood_Vigor,

		/// <summary></summary>
		[Affects("Power")]
		_Primal_Swarm,

		/// <summary></summary>
		[Affects("Power")]
		Primal_Swarm,

		/// <summary></summary>
		[Affects("Power")]
		Thaneborn_Triumph,

		/// <summary></summary>
		[Affects("Power")]
		_Thaneborn_Triumph,

		/// <summary></summary>
		[Affects("Power")]
		Primal_Guardian,

		/// <summary></summary>
		[Affects("Power")]
		_Earthstrength,

		/// <summary></summary>
		[Affects("Power")]
		_Wildblood,

		/// <summary></summary>
		[Affects("Power")]
		Earthstrength,

		/// <summary></summary>
		[Affects("Power")]
		_Second_Failed_Saving_Throw,

		/// <summary></summary>
		[Affects("Power", "Power (Tivaan's Companion Cards)")]
		Instinctive_Effect,

		/// <summary></summary>
		[Affects("Power")]
		Standard_action,

		/// <summary></summary>
		[Affects("Power")]
		_Instinctive_Effect,

		/// <summary></summary>
		[Affects("Power")]
		_Opportunity_Action,

		/// <summary></summary>
		[Affects("Power")]
		_World_Speaker_Spirit,

		/// <summary></summary>
		[Affects("Power")]
		_Lifespirit,

		/// <summary></summary>
		[Affects("Power")]
		_Stormheart,

		/// <summary></summary>
		[Affects("Power")]
		_Orb_of_Imposition,

		/// <summary></summary>
		[Affects("Power")]
		Staff_of_Defense,

		/// <summary></summary>
		[Affects("Power")]
		Wand_of_Accuracy,

		/// <summary></summary>
		[Affects("Power")]
		_Trigger,

		/// <summary></summary>
		[Affects("Power")]
		_Tome_of_Binding,

		/// <summary></summary>
		[Affects("Power")]
		_Wand_of_Accuracy,

		/// <summary></summary>
		[Affects("Power")]
		_Cold,

		/// <summary></summary>
		[Affects("Power")]
		_Radiant,

		/// <summary></summary>
		[Affects("Power")]
		Cosmic_Magic,

		/// <summary></summary>
		[Affects("Power")]
		_Phase_of_the_Sun,

		/// <summary></summary>
		[Affects("Power")]
		_Phase_of_the_Moon,

		/// <summary></summary>
		[Affects("Power")]
		_Phase_of_the_Stars,

		/// <summary></summary>
		[Affects("Power")]
		_Blazing_Sun,

		/// <summary></summary>
		[Affects("Power")]
		_Watching_Moon,

		/// <summary></summary>
		[Affects("Power")]
		_Distant_Stars,

		/// <summary></summary>
		[Affects("Power")]
		_Fire,

		/// <summary></summary>
		[Affects("Power")]
		_Lightning,

		/// <summary></summary>
		[Affects("Power")]
		_Thunder,

		/// <summary></summary>
		[Affects("Power")]
		_Other,

		/// <summary></summary>
		[Affects("Power")]
		Star_Pact,

		/// <summary></summary>
		[Affects("Power")]
		_Lawbreaker_s_Doom,

		/// <summary></summary>
		[Affects("Power")]
		_Augment,

		/// <summary></summary>
		[Affects("Power")]
		Vestige_Pact,

		/// <summary></summary>
		[Affects("Power")]
		_Khaeleth_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Eyes_of_the_Vestige_Augment,

		/// <summary></summary>
		[Affects("Power")]
		_Mount_Vaelis_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Ugar_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Xandor_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Ilmeth_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Shax_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Leraje_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Solis_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Amaan_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Burned_Emperor_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Land_s_Soul_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Queen_of_Namhar,

		/// <summary></summary>
		[Affects("Power")]
		_Master_of_the_Hidden_Flame_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Zuriel_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Karmath_pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Sea_Tyrant_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Each_Failed_Saving_Throw,

		/// <summary></summary>
		[Affects("Power")]
		Censure_of_Pursuit,

		/// <summary></summary>
		[Affects("Power")]
		_Primary_Target,

		/// <summary></summary>
		[Affects("Power")]
		_Primary_Attack,

		/// <summary></summary>
		[Affects("Power")]
		Covenant_of_Wrath,

		/// <summary></summary>
		[Affects("Power")]
		Covenant_of_Malediction,

		/// <summary></summary>
		[Affects("Power")]
		Fey_Pact,

		/// <summary></summary>
		[Affects("Power")]
		Channel_Divnity,

		/// <summary></summary>
		[Affects("Power")]
		No_Action,

		/// <summary></summary>
		[Affects("Power")]
		_No_Action,

/*
		/// <summary></summary>
		[Affects("Power")]
		_Level_13_Swap_Hit,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		_Level_23_Swap_Hit,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		_Level_13_Swap,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		_Level_23_Swap,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		_Level_19_Swap_Hit,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		_Level_29_Swap_Hit,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		_Level_19_Swap_Effect,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		_Level_29_Swap_Effect,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		_Level_11,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		_Level_21,

*/
		/// <summary></summary>
		[Affects("Power")]
		_Thunderborn_Wrath,

		/// <summary></summary>
		[Affects("Power")]
		Primal_Predator,

		/// <summary></summary>
		[Affects("Power")]
		_Watcher_Spirit,

		/// <summary></summary>
		[Affects("Power")]
		_Third_Failed_Saving_Throw,

		/// <summary></summary>
		[Affects("Power")]
		Success,

		/// <summary></summary>
		[Affects("Power")]
		Tertiary_Target,

		/// <summary></summary>
		[Affects("Power")]
		_Keyword,

		/// <summary></summary>
		[Affects("Power")]
		_Chaos_Sorcerer,

		/// <summary></summary>
		[Affects("Power")]
		_Cosmic_Sorcerer,

		/// <summary></summary>
		[Affects("Power")]
		_Axe,

		/// <summary></summary>
		[Affects("Power")]
		_Mace,

		/// <summary></summary>
		[Affects("Power")]
		_Heavy_Blade,

		/// <summary></summary>
		[Affects("Power")]
		_Spear_or_Polearm,

		/// <summary></summary>
		[Affects("Power")]
		_Active_Familiar,

		/// <summary></summary>
		[Affects("Power")]
		_Arcane_Familiar,

		/// <summary></summary>
		[Affects("Power")]
		_Brawler_Style,

		/// <summary></summary>
		[Affects("Power")]
		_Hunter_Fighting_Style,

		/// <summary></summary>
		[Affects("Power")]
		_Brutal_Scoundrel_or_Ruthless_Ruffian,

		/// <summary></summary>
		[Affects("Power")]
		_Insightful_Presence,

		/// <summary></summary>
		[Affects("Power")]
		_Skirmishing_Presence,

		/// <summary></summary>
		[Affects("Power")]
		_Aspect_of_the_Ancients,

		/// <summary></summary>
		[Affects("Power")]
		_Aspect_of_the_Destroyer,

		/// <summary></summary>
		[Affects("Power")]
		_Aspect_of_the_Hunter,

		/// <summary></summary>
		[Affects("Power")]
		_Area,

		/// <summary></summary>
		[Affects("Power")]
		_Close,

		/// <summary></summary>
		[Affects("Power")]
		First_Failed_Saving_Throw,

		/// <summary></summary>
		[Affects("Power")]
		Second_Failed_Saving_Throw,

/*
		/// <summary></summary>
		[Affects("Power")]
		_1_target,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		_2_targets,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		_3,_4,_or_5_targets,

*/
		/// <summary></summary>
		[Affects("Power")]
		_Thaxter_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Baatar_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Unknown_Arcanist_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Kronata_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Vykolad_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Earthen_Maker_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Kulnoghrim_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Ascendant_Commander_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Rune_of_Destruction,

		/// <summary></summary>
		[Affects("Power")]
		_Rune_of_Protection,

		/// <summary></summary>
		[Affects("Power")]
		_Spiritbond,

		/// <summary></summary>
		[Affects("Power")]
		Intrinsic_Nature,

		/// <summary></summary>
		[Affects("Power")]
		Symbiosis,

		/// <summary></summary>
		[Affects("Power")]
		_Secondary_Hit,

		/// <summary></summary>
		[Affects("Power")]
		_Melee,

/*
		/// <summary></summary>
		[Affects("Power")]
		_Level_19_Swap,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		_Level_29_Swap,

*/
		/// <summary></summary>
		[Affects("Power")]
		_Keywords,

/*
		/// <summary></summary>
		[Affects("Power")]
		_1.,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		_2.,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		_3.,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		_4.,

*/
		/// <summary></summary>
		[Affects("Power")]
		_Iron_Soul,

		/// <summary></summary>
		[Affects("Power")]
		_Standard_Action,

		/// <summary></summary>
		[Affects("Power")]
		Sustain_No_Action,

		/// <summary></summary>
		[Affects("Power")]
		Keyword,

		/// <summary></summary>
		[Affects("Power")]
		Area,

		/// <summary></summary>
		[Affects("Power")]
		Close,

		/// <summary></summary>
		[Affects("Power", "Power (Tivaan's Companion Cards)")]
		Opportunity_Action,

		/// <summary></summary>
		[Affects("Magic Item", "Power")]
		Rarity,

		/// <summary></summary>
		[Affects("Magic Item")]
		_IsEnchant,

		/// <summary></summary>
		[Affects("Magic Item")]
		Offhand_Implement_Bonus,

		/// <summary></summary>
		[Affects("Magic Item")]
		_ImplementEquiv,

		/// <summary></summary>
		[Affects("Magic Item")]
		_ImplementForClass,

		/// <summary></summary>
		[Affects("Magic Item")]
		Component,

		/// <summary></summary>
		[Affects("Class Feature", "Class")]
		_DisplayName,

		/// <summary></summary>
		[Affects("Magic Item")]
		Proficient_As,

		/// <summary></summary>
		[Affects("Magic Item")]
		EnchantEquiv,

		/// <summary></summary>
		[Affects("Magic Item")]
		_UniversalImplement,

		/// <summary></summary>
		[Affects("Magic Item")]
		_AlwaysExecute,

		/// <summary></summary>
		[Affects("Magic Item", "Power")]
		Utility_Power,

		/// <summary></summary>
		[Affects("Magic Item")]
		_CannotBeBought,

		/// <summary></summary>
		[Affects("Magic Item", "Weapon", "Class Feature", "Power")]
		_Tags,

		/// <summary></summary>
		[Affects("Magic Item")]
		_Bonus,

		/// <summary></summary>
		[Affects("Magic Item")]
		_Enhancement,

		/// <summary></summary>
		[Affects("Magic Item", "Gear")]
		_AssociatedMonsters,

		/// <summary></summary>
		[Affects("Magic Item")]
		Level_11_Enhancement,

		/// <summary></summary>
		[Affects("Power")]
		Servant_of_the_Staff_Stats,

		/// <summary></summary>
		[Affects("Power")]
		Servant_of_the_Staff_Traits,

		/// <summary></summary>
		[Affects("Power")]
		Servant_of_the_Staff_Defenses,

		/// <summary></summary>
		[Affects("Power")]
		Servant_of_the_Staff_Hit_Points,

		/// <summary></summary>
		[Affects("Power")]
		Servant_of_the_Staff_Speed,

		/// <summary></summary>
		[Affects("Magic Item")]
		Enhancement_Level_11,

		/// <summary></summary>
		[Affects("Magic Item")]
		Disease_Foul_Rotting,

		/// <summary></summary>
		[Affects("Magic Item")]
		Formula_Cost,

		/// <summary></summary>
		[Affects("Companion (Tivaan's Companion Cards)", "Power (Tivaan's Companion Cards)")]
		Standard_Actions,

		/// <summary></summary>
		[Affects("Companion (Tivaan's Companion Cards)", "Power (Tivaan's Companion Cards)")]
		Move_Actions,

		/// <summary></summary>
		[Affects("Companion (Tivaan's Companion Cards)", "Power (Tivaan's Companion Cards)", "Power")]
		Triggered_Actions,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Attributes,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)", "Power")]
		Statistics,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)", "Power")]
		Defenses,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)", "Power")]
		Hit_Points,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)", "Power")]
		Skills,

		/// <summary></summary>
		[Affects("Magic Item")]
		utility_Power,

		/// <summary></summary>
		[Affects("Magic Item", "Power")]
		Attack_Power,

		/// <summary></summary>
		[Affects("Magic Item")]
		Alternative_Reward,

		/// <summary></summary>
		[Affects("Power")]
		Levels,

		/// <summary></summary>
		[Affects("Power", "Power (Tivaan's Companion Cards)")]
		Summoned_Creature,

		/// <summary></summary>
		[Affects("Power")]
		Implacable,

		/// <summary></summary>
		[Affects("Power", "Power (Tivaan's Companion Cards)")]
		Standard_Action,

		/// <summary></summary>
		[Affects("Magic Item")]
		Stone_Grasp,

		/// <summary></summary>
		[Affects("Magic Item")]
		Uitilty_Power,

		/// <summary></summary>
		[Affects("Power")]
		Checking_the_Curse,

		/// <summary></summary>
		[Affects("Background", "Racial Trait", "Feat", "Class Feature", "Power", "Ritual", "Ritual Scroll")]
		Type,

		/// <summary></summary>
		[Affects("Background")]
		Common_Kowledge,

		/// <summary></summary>
		[Affects("Racial Trait")]
		_TraitReplacement,

		/// <summary></summary>
		[Affects("Power")]
		Efect,

		/// <summary></summary>
		[Affects("Power")]
		Animal_Form,

		/// <summary></summary>
		[Affects("Power")]
		_Spellbinding_Beauty,

		/// <summary></summary>
		[Affects("Power")]
		_Wooden_Form,

		/// <summary></summary>
		[Affects("Race")]
		Tribal_Names,

/*
		/// <summary></summary>
		[Affects("Power")]
		1_2_Stinkpot,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		3–4_Firepot,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		5–6_Gluepot,

*/
		/// <summary></summary>
		[Affects("Power")]
		Earth_friend,

		/// <summary></summary>
		[Affects("Power")]
		Earth_Glide,

		/// <summary></summary>
		[Affects("Power")]
		Nonthreatening,

		/// <summary></summary>
		[Affects("Power")]
		DIsplay,

		/// <summary></summary>
		[Affects("Race")]
		Clan_Names,

		/// <summary></summary>
		[Affects("Race")]
		Bladeling_Names,

		/// <summary></summary>
		[Affects("Race")]
		Bladeling_Surnames,

		/// <summary></summary>
		[Affects("Race")]
		Attitudes_and_Beliefs,

		/// <summary></summary>
		[Affects("Race")]
		Tinker_Gnome_Communities,

		/// <summary></summary>
		[Affects("Race")]
		Tinker_Gnomre_Adventurers,

		/// <summary></summary>
		[Affects("Power")]
		Elemental_Spirit,

		/// <summary></summary>
		[Affects("Power")]
		_Sorcerer_King_Pact,

		/// <summary></summary>
		[Affects("Power")]
		_ThemePower,

/*
		/// <summary></summary>
		[Affects("Power")]
		Level_15,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		Level_25,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		Level_13,

*/
		/// <summary></summary>
		[Affects("Power")]
		_Requirement,

/*
		/// <summary></summary>
		[Affects("Power")]
		Level_23,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		Level_17,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		Level_27,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		_Level_23,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		Level_19,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		Level_29,

*/
		/// <summary></summary>
		[Affects("Class Feature", "Power", "Feat")]
		_DisplayAssociates,

		/// <summary></summary>
		[Affects("Power")]
		Summoned_Companion,

		/// <summary></summary>
		[Affects("Power")]
		Move_Action,

		/// <summary></summary>
		[Affects("Power")]
		Immediate_Interrupt,

		/// <summary></summary>
		[Affects("Associate")]
		_Associated_Power,

		/// <summary></summary>
		[Affects("Power")]
		Sarifal_Advisor,

		/// <summary></summary>
		[Affects("Power")]
		Advisor_s_Acumen,

		/// <summary></summary>
		[Affects("Power")]
		Speak_with_Beasts,

		/// <summary></summary>
		[Affects("Power")]
		Battle_Blessing,

/*
		/// <summary></summary>
		[Affects("Power")]
		_?Fetch,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		_?Carry,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		_?Manipulate,

*/
		/// <summary></summary>
		[Affects("Power")]
		Requirment,

		/// <summary></summary>
		[Affects("Power")]
		Passive_Benefits,

		/// <summary></summary>
		[Affects("Power")]
		Active_Benefits,

		/// <summary></summary>
		[Affects("Power")]
		_Hit_Aftereffect,

		/// <summary></summary>
		[Affects("Power")]
		_Miss_Aftereffect,

		/// <summary></summary>
		[Affects("Feat")]
		Rod_Expertise,

		/// <summary></summary>
		[Affects("Trait Package", "Class Feature", "Paragon Path")]
		_CLASSNAME,

		/// <summary></summary>
		[Affects("Class", "Paragon Path")]
		_SUGGESTED_FEATURES,

		/// <summary></summary>
		[Affects("Power")]
		Rules_Item,

/*
		/// <summary></summary>
		[Affects("Power")]
		1_2,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		3_4,

*/
/*
		/// <summary></summary>
		[Affects("Power")]
		5_6,

*/
		/// <summary></summary>
		[Affects("Class Feature")]
		Pact_Reward,

		/// <summary></summary>
		[Affects("Class Feature")]
		_DisplayWeapons,

		/// <summary></summary>
		[Affects("Power")]
		Creature,

		/// <summary></summary>
		[Affects("Power")]
		Origin,

		/// <summary></summary>
		[Affects("Power")]
		Eyes_of_the_Woodland,

		/// <summary></summary>
		[Affects("Power")]
		Special_Movement,

		/// <summary></summary>
		[Affects("Power")]
		Hell_s_Dark_Presence,

		/// <summary></summary>
		[Affects("Power")]
		Vanish_into_the_Void,

		/// <summary></summary>
		[Affects("Power")]
		Shining_Presence,

		/// <summary></summary>
		[Affects("Power")]
		Dancing_Shadows,

		/// <summary></summary>
		[Affects("Power")]
		Death_Throes,

		/// <summary></summary>
		[Affects("Power")]
		Teleporation,

		/// <summary></summary>
		[Affects("Power")]
		Mists_of_Shadow,

		/// <summary></summary>
		[Affects("Power")]
		Invisibility,

		/// <summary></summary>
		[Affects("Power")]
		Soul_Devourer,

		/// <summary></summary>
		[Affects("Power")]
		Teleportation,

		/// <summary></summary>
		[Affects("Power")]
		Disruptive_Tentacles,

		/// <summary></summary>
		[Affects("Power")]
		Child_of_the_Void,

		/// <summary></summary>
		[Affects("Power")]
		Displacement,

		/// <summary></summary>
		[Affects("Power")]
		_Gloom_Pact,

		/// <summary></summary>
		[Affects("Power")]
		_Onyx_Queen_Pact_Boon,

		/// <summary></summary>
		[Affects("Power")]
		_Sustain_Standard,

		/// <summary></summary>
		[Affects("Power")]
		Spellbook,

		/// <summary></summary>
		[Affects("Power")]
		_Secondary_Attack_Type,

		/// <summary></summary>
		[Affects("Power")]
		_Berserker_Fury,

		/// <summary></summary>
		[Affects("Class")]
		Skald_Powers,

		/// <summary></summary>
		[Affects("Power")]
		_SubClasses,

		/// <summary></summary>
		[Affects("Class Feature")]
		Pet_Hit_Points,

		/// <summary></summary>
		[Affects("Class Feature")]
		Pet_Toughness,

		/// <summary></summary>
		[Affects("Class Feature")]
		HALF_CON,

		/// <summary></summary>
		[Affects("Power", "Power (Tivaan's Companion Cards)")]
		Initiative,

		/// <summary></summary>
		[Affects("Power", "Power (Tivaan's Companion Cards)")]
		Perception,

		/// <summary></summary>
		[Affects("Power")]
		Faithful_Pack_Hound,

		/// <summary></summary>
		[Affects("Power")]
		Telepathy,

		/// <summary></summary>
		[Affects("Power")]
		Notes,

		/// <summary></summary>
		[Affects("Power")]
		Guardian_Companion,

		/// <summary></summary>
		[Affects("Power")]
		_Each_Failed_Save,

		/// <summary></summary>
		[Affects("Power")]
		_Water,

		/// <summary></summary>
		[Affects("Power")]
		_Air,

		/// <summary></summary>
		[Affects("Power")]
		_Earth,

		/// <summary></summary>
		[Affects("Power")]
		_Mantle_of_Clarity,

		/// <summary></summary>
		[Affects("Power")]
		_Mantle_of_Elation,

		/// <summary></summary>
		[Affects("Power")]
		_Mantle_of_Impulsiveness,

/*
		/// <summary></summary>
		[Affects("Power")]
		_Close_burst_1,

*/
		/// <summary></summary>
		[Affects("Power")]
		_Night_Stalker,

		/// <summary></summary>
		[Affects("Power")]
		_Bleak_Disciple,

		/// <summary></summary>
		[Affects("Power")]
		Aegis_of_Ensnarement,

		/// <summary></summary>
		[Affects("Power")]
		Information,

		/// <summary></summary>
		[Affects("Power")]
		Light,

		/// <summary></summary>
		[Affects("Power")]
		See_the_Unseen,

		/// <summary></summary>
		[Affects("Power")]
		Deceptive_Move,

		/// <summary></summary>
		[Affects("Power")]
		Owl_s_Eyes,

		/// <summary></summary>
		[Affects("Power")]
		Alchemical_Synergy,

		/// <summary></summary>
		[Affects("Power")]
		Blood_Feast,

		/// <summary></summary>
		[Affects("Power")]
		Dragon_s_Breath,

		/// <summary></summary>
		[Affects("Power")]
		Hunting_Falcon,

		/// <summary></summary>
		[Affects("Power")]
		Rat_s_Cunning,

		/// <summary></summary>
		[Affects("Power")]
		Raven_s_Speech,

		/// <summary></summary>
		[Affects("Power")]
		Independent_Spirit,

		/// <summary></summary>
		[Affects("Power")]
		Serpent_s_Startle,

		/// <summary></summary>
		[Affects("Power")]
		Spider_s_Web,

		/// <summary></summary>
		[Affects("Power")]
		See_All,

		/// <summary></summary>
		[Affects("Power")]
		Devoted_Minion,

		/// <summary></summary>
		[Affects("Power")]
		Tenacious_Guard,

		/// <summary></summary>
		[Affects("Power")]
		Agile_Digits,

		/// <summary></summary>
		[Affects("Power")]
		Lizard_s_Immunity,

		/// <summary></summary>
		[Affects("Power")]
		Ooze_s_Malleability,

		/// <summary></summary>
		[Affects("Power")]
		Parrot_s_Speech,

		/// <summary></summary>
		[Affects("Power")]
		Rootling_Camouflage,

		/// <summary></summary>
		[Affects("Power")]
		Glamered_Scout,

		/// <summary></summary>
		[Affects("Power")]
		Skull_s_Gaze,

		/// <summary></summary>
		[Affects("Power")]
		Toad_s_Healing,

		/// <summary></summary>
		[Affects("Power")]
		Silent_Predator,

		/// <summary></summary>
		[Affects("Power")]
		Form_of_Air,

		/// <summary></summary>
		[Affects("Power")]
		Wisp_s_Escape,

		/// <summary></summary>
		[Affects("Power")]
		Beholderkin_Eye_Ray,

		/// <summary></summary>
		[Affects("Power")]
		Blackspawn_Stealth,

		/// <summary></summary>
		[Affects("Power")]
		Bluespawn_Shock,

		/// <summary></summary>
		[Affects("Power")]
		Form_of_Earth,

		/// <summary></summary>
		[Affects("Power")]
		Form_of_Fire,

		/// <summary></summary>
		[Affects("Power")]
		Grayspawn_Toughness,

		/// <summary></summary>
		[Affects("Power")]
		Greenspawn_s_Diversion,

		/// <summary></summary>
		[Affects("Power")]
		Form_of_Ice,

		/// <summary></summary>
		[Affects("Power")]
		Redspawn_Toughness,

		/// <summary></summary>
		[Affects("Power")]
		Cockatrice_s_Defense,

		/// <summary></summary>
		[Affects("Power")]
		Whitespawn_Minion,

		/// <summary></summary>
		[Affects("Power")]
		Chaos_Echo,

		/// <summary></summary>
		[Affects("Power")]
		Gibbering_Utterances,

		/// <summary></summary>
		[Affects("Power")]
		Shadow_Shroud,

		/// <summary></summary>
		[Affects("Power")]
		His_Own_Bear,

		/// <summary></summary>
		[Affects("Power")]
		Fastieth_Activity,

		/// <summary></summary>
		[Affects("Power")]
		Bloodthorn_Drain,

		/// <summary></summary>
		[Affects("Power")]
		Scorpion_s_Injection,

		/// <summary></summary>
		[Affects("Power")]
		Infuse_Mark,

		/// <summary></summary>
		[Affects("Power")]
		Defensive_Stance,

		/// <summary></summary>
		[Affects("Power")]
		Gadfly_s_Bite,

		/// <summary></summary>
		[Affects("Power")]
		Thieving_Magpie,

		/// <summary></summary>
		[Affects("Power")]
		Monkey_Business,

		/// <summary></summary>
		[Affects("Power")]
		Octopus_s_Flexibility,

		/// <summary></summary>
		[Affects("Power")]
		Saddle_Assistance,

		/// <summary></summary>
		[Affects("Power")]
		Soarwood_Lift,

		/// <summary></summary>
		[Affects("Power")]
		Infuse_Summoned,

		/// <summary></summary>
		[Affects("Power")]
		Book_Bearer,

		/// <summary></summary>
		[Affects("Power")]
		Warforged_Watchfulness,

		/// <summary></summary>
		[Affects("Power")]
		Vine_s_Clasp,

		/// <summary></summary>
		[Affects("Power")]
		Clotting_Factor,

		/// <summary></summary>
		[Affects("Power")]
		Dimensional_Lock,

		/// <summary></summary>
		[Affects("Power")]
		Mobile_Infusion,

		/// <summary></summary>
		[Affects("Power")]
		Foulspawn_Babble,

		/// <summary></summary>
		[Affects("Power")]
		Hammer_s_Ring,

		/// <summary></summary>
		[Affects("Power")]
		Feyling_s_Reservoir,

		/// <summary></summary>
		[Affects("Power")]
		Nightmare_Voice,

		/// <summary></summary>
		[Affects("Power")]
		Silver_Beams,

		/// <summary></summary>
		[Affects("Power")]
		Bearer_of_News,

		/// <summary></summary>
		[Affects("Power")]
		Fate_s_Agent,

		/// <summary></summary>
		[Affects("Power")]
		Gallant_s_Call,

		/// <summary></summary>
		[Affects("Power")]
		Moon_Bite,

		/// <summary></summary>
		[Affects("Power")]
		Incorporeal,

		/// <summary></summary>
		[Affects("Power")]
		Elemental_Servant,

		/// <summary></summary>
		[Affects("Power")]
		Cleaning,

		/// <summary></summary>
		[Affects("Power")]
		Irresistible_Dance,

		/// <summary></summary>
		[Affects("Power")]
		Dazzling_Breath,

		/// <summary></summary>
		[Affects("Power")]
		Feylight_Form,

		/// <summary></summary>
		[Affects("Power")]
		Danger_Sense,

		/// <summary></summary>
		[Affects("Power")]
		Shared_Buoyancy,

		/// <summary></summary>
		[Affects("Power")]
		Overheat,

		/// <summary></summary>
		[Affects("Power")]
		Expert_Forager,

		/// <summary></summary>
		[Affects("Power")]
		Horrific_Aversion,

		/// <summary></summary>
		[Affects("Power")]
		Poisonous_Deterrent,

		/// <summary></summary>
		[Affects("Power")]
		Telepathic_Mimicry,

		/// <summary></summary>
		[Affects("Power")]
		Empathic_Guidance,

		/// <summary></summary>
		[Affects("Power")]
		Piercing_Scream,

		/// <summary></summary>
		[Affects("Power")]
		Under_Raven_s_Wing,

		/// <summary></summary>
		[Affects("Power")]
		Animal_Companion,

		/// <summary></summary>
		[Affects("Power")]
		Cat_s_Stealth,

		/// <summary></summary>
		[Affects("Power")]
		Distracting_Attack,

		/// <summary></summary>
		[Affects("Power")]
		On_the_Track,

		/// <summary></summary>
		[Affects("Power")]
		Hawk_s_Eye,

		/// <summary></summary>
		[Affects("Power")]
		Nimble_Fingers,

		/// <summary></summary>
		[Affects("Power")]
		Snatch_and_Scoot,

		/// <summary></summary>
		[Affects("Power")]
		Tentacle,

		/// <summary></summary>
		[Affects("Power")]
		Blinking_Pack,

		/// <summary></summary>
		[Affects("Power")]
		Blinking_Bite,

		/// <summary></summary>
		[Affects("Power")]
		Alert_Companion,

		/// <summary></summary>
		[Affects("Power")]
		Claw,

		/// <summary></summary>
		[Affects("Power")]
		Ferocious_Companion,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Companion,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Healing_Surge_Value,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Phantom_on_the_Wind,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Brittle_Skin,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Triggered_Action,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Frozen_in_Place,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Heart_of_Flame,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Aquatic,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Sensitive_to_Cold,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Dust_and_Smoke,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Resistance,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Passive_Benefit_Frost_Armor,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Active_Benefit_Minor_Action,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Passive_Benefit_Self_Repair,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Active_Benefit_Fearsome_Presence,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Active_Benefit_Immediate_Interrupt,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Passive_Benefit_Mad_Delusions,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Passive_Benefit_Uncanny_Senses_and_Grip,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Active_Benefit_Free_Action,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Passive_Benefit_Burning_Inside,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Passive_Benefit_Fire_Within,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Active_Benefit_Flickering_Flames,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Active_Benefit_Move_Action,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Passive_Benefit_Vicious,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Passive_Benefit_Rattle_the_Cage,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Active_Benefit_Standard_Action,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Active_Benefits_Immediate_Interrupt,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Passive_Benefit_Corrosive_Secretions,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Passive_Benefit_Unnatural_Flexibility,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Active_Benefit_Noxious_Vapors,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Active_Benefits_Move_Action,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Passive_Benefit_Fiery_Intensity,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Passive_Benefit_Flowing_Lava,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Active_Benefit_Immediate_Reaction,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Passive_Benefit_Aquatic,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Active_Benefit_Aquatic,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Passive_Benefit_Stone_s_Resilience,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Active_Benefit_Earth_Glide,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Passive_Benefit_Storm_Dancer,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Active_Benefit_Soaring_Talon,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Active_Benefit_Eye_of_the_Storm,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Passive_Benefit_Ephemeral_Wings,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Passive_Benefit_Ethereal_Personality,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Active_Benefit_Buffeting_Winds,

		/// <summary></summary>
		[Affects("Power", "Power (Tivaan's Companion Cards)")]
		Gift_of_Stone,

		/// <summary></summary>
		[Affects("Power", "Power (Tivaan's Companion Cards)")]
		Gift_of_Wind,

		/// <summary></summary>
		[Affects("Power")]
		Gift_of_Flame,

		/// <summary></summary>
		[Affects("Power", "Power (Tivaan's Companion Cards)")]
		Gift_of_Water,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Formed_from_Fire,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Cover,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Fluttering_Form,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Shattering_Tremors,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Gift_of_Fire,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Guttering_Flames,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Frozen_Waves,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Stone_Body,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Agile_Flames,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Icy_Strength,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Storm_Sight,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Debris_Cloud,

		/// <summary></summary>
		[Affects("Power (Tivaan's Companion Cards)")]
		Animal_Attack,

		/// <summary></summary>
		[Affects("Companion", "Power")]
		Mount_Companion,

		/// <summary></summary>
		[Affects("Companion")]
		Manipulate_Items,

		/// <summary></summary>
		[Affects("Power")]
		Tempter_s_Influence,

		/// <summary></summary>
		[Affects("Power")]
		Bite,

		/// <summary></summary>
		[Affects("Power")]
		Demonic_Lore,

		/// <summary></summary>
		[Affects("Power")]
		Vengeful_Temptation,

		/// <summary></summary>
		[Affects("Power")]
		Piercing_Charger,

		/// <summary></summary>
		[Affects("Power")]
		Kick,

		/// <summary></summary>
		[Affects("Power")]
		Fey_Step,

		/// <summary></summary>
		[Affects("Power")]
		Horn_Touch,

		/// <summary></summary>
		[Affects("Power")]
		Traits,

		/// <summary></summary>
		[Affects("Power")]
		Mists_of_Pluton,

		/// <summary></summary>
		[Affects("Power")]
		Detect_Arcana,

		/// <summary></summary>
		[Affects("Power")]
		Immunities,

		/// <summary></summary>
		[Affects("Power")]
		Countermeasures,


    }
    [AttributeUsage(AttributeTargets.All)]
    sealed class AffectsAttribute : Attribute
    {
        public AffectsAttribute(params string[] affects)
        {
            this.Affects = affects;
        }

        public string[] Affects { get; private set; }
    }
    [AttributeUsage(AttributeTargets.All)]
    sealed class UsageAttribute : Attribute
    {
        public UsageAttribute(string mode)
        {
            this.Mode = mode;
        }

        public string Mode { get; private set; }
    }
}
